---
title: "CoffeevsTea"
author: "Bazgan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
tea_coffee <- read.csv("tea_vs_coffee_global_final.csv", stringsAsFactors = FALSE)

head(tea_coffee)
dim(tea_coffee)
names(tea_coffee)
str(tea_coffee)
summary(tea_coffee)

tea_coffee$drink_preference <- as.factor(tea_coffee$drink_preference)

tea_coffee$country <- NULL
tea_coffee$continent <- NULL
tea_coffee$favorite_drink <- NULL
tea_coffee$drink_category <- NULL
tea_coffee$caffeine_preference <- NULL

tea_coffee[] <- lapply(tea_coffee, function(x) {
  if (is.character(x)) as.factor(x) else x
})

set.seed(123)

train_index <- sample(1:nrow(tea_coffee), 0.7 * nrow(tea_coffee))
train_data <- tea_coffee[train_index, ]
test_data <- tea_coffee[-train_index, ]

model_glm <- glm(drink_preference ~ ., data = train_data, family = binomial)

summary(model_glm)

prob <- predict(model_glm, test_data, type = "response")

levels(train_data$drink_preference)

pred <- ifelse(prob > 0.5, "Tea", "Coffee")
pred <- factor(pred, levels = levels(test_data$drink_preference))

table(pred, test_data$drink_preference)

mean(pred == test_data$drink_preference)

library(rpart)
library(rpart.plot)


tree_model <- rpart(
  drink_preference ~ ., 
  data = train_data, 
  method = "class",
  control = rpart.control(cp =  0.0074233, minsplit = 20)
)

rpart.plot(tree_model)


printcp(tree_model)
plotcp(tree_model)

pruned_tree <- prune(tree_model, cp = 0.0074233)
rpart.plot(pruned_tree)

tree_pred <- predict(pruned_tree, test_data, type = "class")

table(tree_pred, test_data$drink_preference)
mean(tree_pred == test_data$drink_preference)

library(randomForest)

rf_model <- randomForest(drink_preference ~ ., data = train_data)

rf_pred <- predict(rf_model, test_data)

table(rf_pred, test_data$drink_preference)
mean(rf_pred == test_data$drink_preference)
```

